### ISSUE TITLE
Time to update to Zstandard v1.2.0

### ISSUE THREAD

**Issue by AlexIvamoto** [mururu/zstd-erlang#1]
v1.0 released this on 31 Aug 2016 - it's time to update to Zstandard v1.2.0 ?

**Comment by jjl** [comment]
July 6 2017, 1.3.0 was released

**Comment by mururu** [comment]
I'll update it in a few days.

**Comment by mururu** [comment]
Updated to v1.3.3. https://github.com/mururu/zstd-erlang/pull/3
